title: "Design Tools"
description: "High-performance Grasshopper components for industrial design."

# This tells GitHub to pull the community theme directly from its repository
remote_theme: just-the-docs/just-the-docs

# Enable the built-in search engine
search_enabled: true

collections:
  zh:
    output: true
    permalink: /zh/:path/

just_the_docs:
  collections:
    zh:
      name: "中文"
      nav_fold: true # Folds the collection under an accordion drop-down by default